[features]
seeds = false
skip-lint = false

[programs.devnet]
myepicproject = "GqtKLAH7g1NvTYbAb5EhS9CzLyAQDFiQuHakRFMGMqvq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/krysthianmartins/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
